name = "rss-worker"
main = "src/worker.js"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
send_metrics = false

# [build]
# command = "npm run build"
# cwd = "dist"
# watch_dir = "dist"
